export const auctionList = [
  {
    //? ============== BEFORE EVENT ============= ?//
    id: 1,
    addres: "Jl. Raya Nusa Dua Selatan, Benoa, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",
    place_name: "Apurva Kempinski Bali",
    title: "Auction 1",
    thumbnail: "/images/artwork-1.jpg",
    start_date: "2023-12-25T00:00:00.000Z",
    end_date: "2023-12-30T00:00:00.000Z",
    slug: "auction-1",
    status: "COMING SOON",
    details:
      "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nishendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscing justultrices interdum tristique mi. Odio ac dignissim odio id in massa eget id morbiRidiculus a vitae dignissim massa cras imperdiet massa. At id quis tempus pretiu tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverrarcu tempor adipiscing arcu nunc. Hendrerit consectetur interdum cursus ut nibh ac nisaliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nullsollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc Penatibus tincidunt ultrices mauris erat. Erat mus integer nibh adipiscing ac adipiscingeget mauris dui <br /> Nam id massa sodales aliquam bibendum. Vulputate malesuada pretium eu adipiscin volutpat. Faucibus dui vitae et dictum arcu aliquam vestibulum vitae. Id arcu phaselluin mauris pellentesque pulvinar ornare. Proin vivamus mi ipsum cursus faucibus nunsollicitudin arcu venenatis. Nullam sociis diam ",
    visi: "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
    misi: "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
    overview: {
      title: "Auction 1 Bali Kempinski",
      description:
        "Lorem ipsum dolor sit amet consectetur. Vel adipiscing urna sagittis faucibus pharetra.Tempor pellentesque congue odio tempus etiam. Ipsum eu arcu aliquam massa. Vestibulumconsequat malesuada commodo quam nulla varius nisl tortor. Odio convallis fames eratsollicitudin netus. Neque egestas bibendum sit facilisis ultrices gravida ullamcorper massa. In porta quis tellus fermentum arcu nisl pellentesque cras. Eu etiam rhoncusaenean fringilla duis ultrices justo aliquet ullamcorper.",
      video_url: "https://youtu.be/3orkmMlSpmI",
      auction_img: [
        { id: 1, img_url: "/images/artwork-1.jpg" },
        { id: 2, img_url: "/images/artwork-2.jpg" },
        { id: 3, img_url: "/images/artwork-3.jpg" },
        { id: 4, img_url: "/images/artwork-4.jpg" },
      ],
    },
    curator: [
      {
        id: 1,
        name: "Curator Name 1",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-1.jpg",
        position: "Curator",
      },
      {
        id: 2,
        name: "Curator Name ",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-2.jpg",
        position: "Curator",
      },
      {
        id: 3,
        name: "Curator Name 3",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-3.jpg",
        position: "Curator",
      },
      {
        id: 4,
        name: "Curator Name 4",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-4.jpg",
        position: "Curator",
      },
    ],
    lots: [
      {
        id: 1,
        imgUrl: "/images/artwork-1.jpg",
        title: "Artwork Auction 1",
        slug: "artwork-auction-1",
        artist: "Artist Name",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },
      {
        id: 2,
        imgUrl: "/images/artwork-2.jpg",
        title: "Artwork Auction 2",
        slug: "artwork-auction-2",
        artist: "",
        media: "Acrylic on Canvas",

        condition: "Good",
        description: "Artwork auction 1 description",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "ENDED",
      },

      {
        id: 3,
        imgUrl: "/images/artwork-3.jpg",
        title: "Artwork Auction 3",
        slug: "artwork-auction-3",
        artist: "",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },

      {
        id: 4,
        imgUrl: "/images/artwork-4.jpg",
        title: "Artwork Auction 4",
        slug: "artwork-auction-4",
        artist: "",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },

      {
        id: 5,
        imgUrl: "/images/artwork-5.jpg",
        title: "Artwork Auction 5",
        slug: "artwork-auction-5",
        artist: "",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },
    ],
  },
  {
    //? ============== IN EVENT ============= ?//
    id: 2,
    title: "Auction 2",
    addres: "Jl. Raya Nusa Dua Selatan, Benoa, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",
    place_name: "Apurva Kempinski Bali",

    thumbnail: "/images/artwork-5.jpg",

    start_date: "2023-04-29T16:26:08.667Z",
    end_date: "2023-08-29T16:26:08.667Z",
    slug: "auction-2",
    status: "LIVE NOW",
    details:
      "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nishendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscing justultrices interdum tristique mi. Odio ac dignissim odio id in massa eget id morbiRidiculus a vitae dignissim massa cras imperdiet massa. At id quis tempus pretiu tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverrarcu tempor adipiscing arcu nunc. Hendrerit consectetur interdum cursus ut nibh ac nisaliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nullsollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc Penatibus tincidunt ultrices mauris erat. Erat mus integer nibh adipiscing ac adipiscingeget mauris dui <br /> Nam id massa sodales aliquam bibendum. Vulputate malesuada pretium eu adipiscin volutpat. Faucibus dui vitae et dictum arcu aliquam vestibulum vitae. Id arcu phaselluin mauris pellentesque pulvinar ornare. Proin vivamus mi ipsum cursus faucibus nunsollicitudin arcu venenatis. Nullam sociis diam ",
    visi: "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
    misi: "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
    overview: {
      title: "Auction 1 Bali Kempinski",
      description:
        "Lorem ipsum dolor sit amet consectetur. Vel adipiscing urna sagittis faucibus pharetra.Tempor pellentesque congue odio tempus etiam. Ipsum eu arcu aliquam massa. Vestibulumconsequat malesuada commodo quam nulla varius nisl tortor. Odio convallis fames eratsollicitudin netus. Neque egestas bibendum sit facilisis ultrices gravida ullamcorper massa. In porta quis tellus fermentum arcu nisl pellentesque cras. Eu etiam rhoncusaenean fringilla duis ultrices justo aliquet ullamcorper.",
      video_url: "https://youtu.be/jcPOcS6BAM8",
      auction_img: [
        { id: 1, img_url: "/images/artwork-1.jpg" },
        { id: 2, img_url: "/images/artwork-2.jpg" },
        { id: 3, img_url: "/images/artwork-3.jpg" },
        { id: 4, img_url: "/images/artwork-4.jpg" },
      ],
    },
    curator: [
      {
        id: 1,
        name: "Curator Name 1",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-1.jpg",
        position: "Curator",
      },
      {
        id: 2,
        name: "Curator Name ",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-1.jpg",
        position: "Curator",
      },
      {
        id: 3,
        name: "Curator Name 3",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-1.jpg",
        position: "Curator",
      },
      {
        id: 4,
        name: "Curator Name 4",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-1.jpg",
        position: "Curator",
      },
    ],
    lots: [
      {
        id: 1,
        imgUrl: "/images/artwork-1.jpg",
        title: "Artwork Auction 1",
        slug: "artwork-auction-1",
        artist: "Artist Name",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },
      {
        id: 2,
        imgUrl: "/images/artwork-2.jpg",
        title: "Artwork Auction 2",
        slug: "artwork-auction-2",
        artist: "",
        media: "Acrylic on Canvas",

        condition: "Good",
        description: "Artwork auction 1 description",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "ENDED",
      },

      {
        id: 3,
        imgUrl: "/images/artwork-3.jpg",
        title: "Artwork Auction 3",
        slug: "artwork-auction-3",
        artist: "",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },

      {
        id: 4,
        imgUrl: "/images/artwork-4.jpg",
        title: "Artwork Auction 4",
        slug: "artwork-auction-4",
        artist: "",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },

      {
        id: 5,
        imgUrl: "/images/artwork-5.jpg",
        title: "Artwork Auction 5",
        slug: "artwork-auction-5",
        artist: "",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },
    ],
  },
  {
    //? ============== AFTER EVENT ============= ?//
    id: 3,
    title: "Auction 3",
    addres: "Jl. Raya Nusa Dua Selatan, Benoa, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",
    place_name: "Apurva Kempinski Bali",

    thumbnail: "/images/artwork-6.jpg",
    start_date: "2022-04-29T16:26:08.667Z",
    end_date: "2022-05-29T16:26:08.667Z",
    slug: "auction-3",
    status: "ENDED",
    details:
      "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nishendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscing justultrices interdum tristique mi. Odio ac dignissim odio id in massa eget id morbiRidiculus a vitae dignissim massa cras imperdiet massa. At id quis tempus pretiu tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverrarcu tempor adipiscing arcu nunc. Hendrerit consectetur interdum cursus ut nibh ac nisaliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nullsollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc Penatibus tincidunt ultrices mauris erat. Erat mus integer nibh adipiscing ac adipiscingeget mauris dui <br /> Nam id massa sodales aliquam bibendum. Vulputate malesuada pretium eu adipiscin volutpat. Faucibus dui vitae et dictum arcu aliquam vestibulum vitae. Id arcu phaselluin mauris pellentesque pulvinar ornare. Proin vivamus mi ipsum cursus faucibus nunsollicitudin arcu venenatis. Nullam sociis diam ",
    visi: "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
    misi: "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
    overview: {
      title: "Auction 1 Bali Kempinski",
      description:
        "Lorem ipsum dolor sit amet consectetur. Vel adipiscing urna sagittis faucibus pharetra.Tempor pellentesque congue odio tempus etiam. Ipsum eu arcu aliquam massa. Vestibulumconsequat malesuada commodo quam nulla varius nisl tortor. Odio convallis fames eratsollicitudin netus. Neque egestas bibendum sit facilisis ultrices gravida ullamcorper massa. In porta quis tellus fermentum arcu nisl pellentesque cras. Eu etiam rhoncusaenean fringilla duis ultrices justo aliquet ullamcorper.",
      video_url: "https://youtu.be/PgulsPa8jzs",
      auction_img: [
        { id: 1, img_url: "/images/artwork-1.jpg" },
        { id: 2, img_url: "/images/artwork-2.jpg" },
        { id: 3, img_url: "/images/artwork-3.jpg" },
        { id: 4, img_url: "/images/artwork-4.jpg" },
      ],
    },
    curator: [
      {
        id: 1,
        name: "Curator Name 1",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-1.jpg",
        position: "Curator",
      },
      {
        id: 2,
        name: "Curator Name ",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-1.jpg",
        position: "Curator",
      },
      {
        id: 3,
        name: "Curator Name 3",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-1.jpg",
        position: "Curator",
      },
      {
        id: 4,
        name: "Curator Name 4",
        background:
          "Lorem ipsum dolor sit amet consectetur. Volutpat condimentum vitae etiam magnis. Nisihendrerit euismod neque morbi duis vitae ullamcorper. Quam laoreet orci adipiscingjusto ultrices interdum tristique mi. Odio ac dignissim odio id in massa eget idmorbi. Ridiculus a vitae dignissim massa cras imperdiet massa. At id quis tempuspretium tincidunt dapibus. Sed turpis pellentesque nisl lacus a libero aliquet suscipit. Viverra arcu tempor adipiscing arcu nunc. Hendrerit consectetur interdumcursus ut nibh ac nisl aliquam. Et convallis feugiat dui tellus elementum lacus. Nunc velit mollis nulla sollicitudin et augue velit nisl massa. Accumsan sed egestas enim in dictum turpis nunc. Penatibus tincidunt ultrices mauris erat. Erat mus integer nibhadipiscing ac adipiscing eget mauris dui.",
        img_url: "/images/profile-1.jpg",
        position: "Curator",
      },
    ],
    lots: [
      {
        id: 1,
        imgUrl: "/images/artwork-1.jpg",
        title: "Artwork Auction 1",
        slug: "artwork-auction-1",
        artist: "Artist Name",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },
      {
        id: 2,
        imgUrl: "/images/artwork-2.jpg",
        title: "Artwork Auction 2",
        slug: "artwork-auction-2",
        artist: "",
        media: "Acrylic on Canvas",

        condition: "Good",
        description: "Artwork auction 1 description",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "ENDED",
      },

      {
        id: 3,
        imgUrl: "/images/artwork-3.jpg",
        title: "Artwork Auction 3",
        slug: "artwork-auction-3",
        artist: "",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },

      {
        id: 4,
        imgUrl: "/images/artwork-4.jpg",
        title: "Artwork Auction 4",
        slug: "artwork-auction-4",
        artist: "",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },

      {
        id: 5,
        imgUrl: "/images/artwork-5.jpg",
        title: "Artwork Auction 5",
        slug: "artwork-auction-5",
        artist: "",
        condition: "Good",
        description: "Artwork auction 1 description",
        media: "Acrylic on Canvas",
        estimation: " 6.000.000",
        current: " 5.000.000",
        start_date: "2022-04-29T16:26:08.667Z",
        end_date: "2022-04-29T16:26:08.667Z",
        imgHeight: "200",
        imgWidth: "200",
        status: "READY",
      },
    ],
  },
];
