export const logoDummy = [
  { logo: "/images/visa.svg" },
  { logo: "/images/mastercard.svg" },
  { logo: "/images/jcb.svg" },
  { logo: "/images/amex.svg" },
  { logo: "/images/bca-klikpay.svg" },
  { logo: "/images/octo-clicks.svg" },
  { logo: "/images/danamon-ob.svg" },
  { logo: "/images/bca.svg" },
  { logo: "/images/permata.svg" },
  { logo: "/images/mandiri.svg" },
  { logo: "/images/bni.svg" },
  { logo: "/images/bri.svg" },
  { logo: "/images/bank-building.svg" },
  { logo: "/images/indomaret.svg" },
  { logo: "/images/isaku.svg" },
  { logo: "/images/akulaku.svg" },
  { logo: "/images/alfamart.svg" },
  { logo: "/images/alfamidi.svg" },
  { logo: "/images/dandan.svg" },
  { logo: "/images/uob.svg" },
  { logo: "/images/shopeepay.svg" },
  { logo: "/images/qris.svg" },
];
